"""Paraphrase generation for output-consistency measurement.

Per ``docs/METHODOLOGY.md`` §1.1: K=5 paraphrases of each task input,
generated by ``gpt-5.2`` (per ADR-0001) with the frozen prompt at
``prompts/paraphrase_v1.txt``, temperature 0.7. A second LLM call
validates semantic equivalence to the original; rejected paraphrases
are regenerated up to 3 times.

The K=5 / N=10 distinction is intentional: paraphrases are *different*
inputs run once each, not the same input run N times (METHODOLOGY §1.1
clarification per ADR-0004 §A).

Rejection rate is reported as a quality metric on each
:class:`ParaphraseSet` — consistently high rejection suggests the
generator or validator prompt may be miscalibrated and is itself a
quality signal worth surfacing in run reports
(``docs/WEEK_1.md`` §"What can go wrong" #3).
"""

from __future__ import annotations

import re
from typing import Final

from pydantic import BaseModel, ConfigDict, Field

from steadfast._llm_parsing import load_prompt, try_parse_strict
from steadfast.models.base import BaseModelClient

PARAPHRASE_PROMPT_VERSION: Final[str] = "v1"
DEFAULT_PARAPHRASE_MODEL: Final[str] = "gpt-5.2"
DEFAULT_TEMPERATURE: Final[float] = 0.7

# Single-pass placeholder regex for prompt rendering — same pattern as
# the rubric judge (ADR-0003 §B.4 lessons): protects against
# user-provided text containing literal ``{k}`` or ``{original}``
# placeholders triggering double substitution.
_PARAPHRASE_PLACEHOLDER_RE = re.compile(r"\{(k|original)\}")
_VALIDATOR_PLACEHOLDER_RE = re.compile(r"\{(original|paraphrase)\}")


class _ParaphraseList(BaseModel):
    """Schema for the generator's JSON output."""

    paraphrases: list[str]


class _ValidatorOutput(BaseModel):
    """Schema for the validator's JSON output."""

    equivalent: bool
    reason: str


class ParaphraseSet(BaseModel):
    """K validated paraphrases of an original input.

    ``rejection_rate`` = ``rejected / (accepted + rejected)`` over the
    validator's lifetime for this generation, capped by ``max_retries``.
    Tracked as a quality signal — high rates suggest the generator or
    validator prompt may need recalibration.
    """

    model_config = ConfigDict(frozen=True)

    original: str
    paraphrases: list[str]
    requested_k: int = Field(ge=1)
    accepted: int = Field(ge=0)
    rejected: int = Field(ge=0)
    rejection_rate: float = Field(ge=0.0, le=1.0)
    prompt_version: str = PARAPHRASE_PROMPT_VERSION
    generator_model: str
    validator_model: str


class ParaphraseError(RuntimeError):
    """Raised when paraphrase generation can't produce K valid paraphrases."""


def _render_generator_prompt(*, template: str, k: int, original: str) -> str:
    values = {"k": str(k), "original": original}
    return _PARAPHRASE_PLACEHOLDER_RE.sub(lambda m: values[m.group(1)], template)


def _render_validator_prompt(*, template: str, original: str, paraphrase: str) -> str:
    values = {"original": original, "paraphrase": paraphrase}
    return _VALIDATOR_PLACEHOLDER_RE.sub(lambda m: values[m.group(1)], template)


async def _validate_paraphrase(
    *,
    client: BaseModelClient,
    model: str,
    template: str,
    original: str,
    paraphrase: str,
) -> bool:
    """Ask the validator if ``paraphrase`` preserves ``original``'s meaning.

    Conservative on parse failure — treats unparseable validator output
    as a rejection. Validator parse failures should be rare with a frozen
    prompt and a strong infrastructure model; counting them as rejections
    keeps the rejection-rate metric honest about validator instability.
    """
    prompt = _render_validator_prompt(template=template, original=original, paraphrase=paraphrase)
    response = await client.acomplete(prompt, model=model, temperature=0.0)
    parsed = try_parse_strict(response.text, _ValidatorOutput)
    if parsed is None:
        return False
    return parsed.equivalent


async def generate_paraphrases(
    *,
    original: str,
    k: int = 5,
    client: BaseModelClient,
    model: str = DEFAULT_PARAPHRASE_MODEL,
    max_retries: int = 3,
    seed: int | None = None,
) -> ParaphraseSet:
    """Generate ``k`` validated paraphrases of ``original``.

    Calls the generator (frozen prompt at ``prompts/paraphrase_v1.txt``)
    asking for the number of paraphrases still needed; each candidate is
    individually validated by a second LLM call. Up to ``max_retries``
    generator passes are made; if K valid paraphrases still aren't
    accumulated, raises :class:`ParaphraseError`.

    Both generator and validator use the same ``model`` (per ADR-0001
    the v0.1 lock is ``gpt-5.2``); a future version may split them.
    """
    if k < 1:
        raise ValueError("k must be >= 1")
    if max_retries < 1:
        raise ValueError("max_retries must be >= 1")

    generator_template = load_prompt("paraphrase_v1.txt")
    validator_template = load_prompt("paraphrase_validate_v1.txt")

    accepted: list[str] = []
    rejected_count = 0

    for attempt in range(max_retries):
        if len(accepted) >= k:
            break
        needed = k - len(accepted)

        gen_prompt = _render_generator_prompt(
            template=generator_template, k=needed, original=original
        )
        # Some OpenAI-family models accept ``seed``; pass it (and bump per
        # attempt so retries don't re-roll the same generation).
        # Temperature drives the surface diversity per METHODOLOGY §1.1.
        kwargs: dict[str, object] = {"temperature": DEFAULT_TEMPERATURE}
        if seed is not None:
            kwargs["seed"] = seed + attempt

        try:
            response = await client.acomplete(gen_prompt, model=model, **kwargs)
        except Exception:
            # Transient generator failures are absorbed at the rep level
            # (the model client already retries on transient errors per
            # ADR-0002 §B.2); anything reaching here is non-retryable.
            # Try the next attempt — if every attempt errors we fall
            # through to the ParaphraseError below.
            continue

        parsed = try_parse_strict(response.text, _ParaphraseList)
        if parsed is None:
            continue

        for candidate in parsed.paraphrases:
            if len(accepted) >= k:
                break
            ok = await _validate_paraphrase(
                client=client,
                model=model,
                template=validator_template,
                original=original,
                paraphrase=candidate,
            )
            if ok:
                accepted.append(candidate)
            else:
                rejected_count += 1

    if len(accepted) < k:
        raise ParaphraseError(
            f"could not generate {k} valid paraphrases of "
            f"{original[:60]!r}... after {max_retries} retries "
            f"(accepted={len(accepted)}, rejected={rejected_count})"
        )

    total_attempts = len(accepted) + rejected_count
    rejection_rate = rejected_count / total_attempts if total_attempts > 0 else 0.0

    return ParaphraseSet(
        original=original,
        paraphrases=accepted[:k],
        requested_k=k,
        accepted=len(accepted),
        rejected=rejected_count,
        rejection_rate=rejection_rate,
        generator_model=model,
        validator_model=model,
    )
