import pilotJson from "@/data/pilot.json";
import type { Pilot } from "./types";

// The pilot.json file is the build-time snapshot generated by
// scripts/build_leaderboard_data.py. It is the single source of truth
// for the leaderboard's data; the underlying results/ directory is
// gitignored, so the leaderboard never reads it at runtime.
export const pilot = pilotJson as unknown as Pilot;
